#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------
 
version: '3.7'
services:
  dapr-java-sdk:
    build:
      context: ../
      dockerfile: ./.devcontainer/devsdk-maven.dockerfile
    
    environment:
      DAPR_NETWORK: dapr
      DAPR_REDIS_HOST: dapr_redis
      DAPR_PLACEMENT_HOST: dapr_placement

    volumes:
      # This is where VS Code should expect to find your project's source code
      # and the value of "workspaceFolder" in .devcontainer/devcontainer.json
      - ..:/dapr
      - volume-dapr-vscode:/home/root
      - /var/run/docker.sock:/var/run/docker.sock 
  
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done" 

  
volumes:
  volume-dapr-vscode:
    labels:
      - "dapr=java-sdk-maven"

networks:
  default:
    name: dapr